name: 构建sb镜像

on:
  # push:
  # push | pull_request push和pull_request触发
  # 手动触发
  workflow_dispatch:
    inputs:
      tag: 
        description: "镜像tag"
        # required: false
        # default: 'latest'

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Checkout sb repository
        uses: actions/checkout@v3
        with:
          repository:  SagerNet/sing-box
          path: sing-box
          fetch-depth: 0 
      - name: Setup QEMU for Docker Buildx
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set build tag
        id: tag
        run: |
          echo "latest=ghcr.io/alinuxsa/sbox:latest" >> $GITHUB_OUTPUT
          if [[ -z "${{ github.event.inputs.tag }}" ]]; then
            echo "versioned=ghcr.io/alinuxsa/sbox:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "versioned=ghcr.io/alinuxsa/sbox:${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: sing-box
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          tags: |
            ${{ steps.tag.outputs.latest }}
            ${{ steps.tag.outputs.versioned }}